# Generated by Django 5.1.7 on 2025-03-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
