# Generated by Django 5.1.7 on 2025-03-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_clients_gemi_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='title',
            field=models.CharField(max_length=90),
        ),
    ]
